export const ColorsActionTypes = {
    SET_CURRENT_FONT_COLORS: "SET_CURRENT_FONT_COLORS",
    SET_CURRENT_HEADER_COLOR: "SET_CURRENT_HEADER_COLOR",
    SET_CURRENT_FOOTER_COLOR: "SET_CURRENT_FOOTER_COLOR"
}