const WebinarQueuetListActionTypes = {
    SET_PRODUCT_LIST_ITEMS: "SET_PRODUCT_LIST_ITEMS",
    SET_FILTER_STRING: "SET_FILTER_STRING",
    SET_LIMIT_PER_PAGE: "SET_LIMIT_PER_PAGE",
    SET_PRODUCT_LIST_PAGE_NUM: "SET_PRODUCT_PAGE_NUM",
    SET_MAX_WEBINAR_COUNT: "SET_MAX_WEBINAR_COUNT"
};

export default WebinarQueuetListActionTypes;