export const ProductDetailActionTypes = {
    SET_CURRENT_PRODUCT_DETAIL: "SET_CURRENT_PRODUCT_DETAIL",
    SET_CURRENT_PRODUCT_COMMENTS: "SET_CURRENT_PRODUCT_COMMENTS",
    ADD_OWN_COMMENT: "ADD_OWN_COMMENT",
    ADD_REPLIED_COMMENT: "ADD_REPLIED_COMMENT"
}